### ISSUE TITLE
Client Side Errors on Firefox

### ISSUE THREAD

**Issue by rhaskia** [hackclub/scrapbook#590] opened 2023-09-29 05:03 UTC
On loading up the scrapbook website, it shows briefly before saying a client-side exception has occurred.
Errors:
Uncaught Error: Minified React error #425; visit https://reactjs.org/docs/error-decoder.html?invariant=425 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful 
Uncaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
ReferenceError: emailToPfp is not defined

**Comment by grymmy** [comment] 2023-10-21 00:11
Closing this as a duplicate of #591

**Closed by grymmy** 2023-10-21 00:11 UTC
