### ISSUE TITLE
Scrappy gives you more streaks than you actually have

### ISSUE THREAD

**Issue by Irtaza2009** [hackclub/scrapbook#800] opened 2024-07-18 22:48 UTC
**Just found a bug in Scrapbook.**
If you submit multiple posts in one day in #scrapbook, it only increments the streak by 1 and then tells you that you already have the streak for that day for the rest of the posts. If you submitted e.g. 4 projects in a single day and you have a 0 streak, then it will increment by 1 so now you have a 1 day streak. But if you post again in #scrapbook the next day (your 5th post), you will have a streak of 5 days.

I am not sure whether to report this bug in Scrapbook or Scrappy, but for now, I am submitting it here.

**Comment by JosiasAurel** [comment] 2024-08-13 05:36
Hey, I'm unable to reproduce this issue. Closing for now. Please re-open if this happens again!

**Closed by JosiasAurel** 2024-08-13 05:36 UTC
