### ISSUE TITLE
Streak counting bug

### ISSUE THREAD

**Issue by Shrey-Mehra** [hackclub/scrapbook#514] opened 2023-05-10 14:30 UTC
![Screenshot 2023-05-10 195134](https://github.com/hackclub/scrapbook/assets/85977707/bf4c8423-368e-4f5f-80a9-0a37d78cf861)
There is a bug in streak counting like with 1 Day delay Scrapbook Streak is Regular

**Comment by JosiasAurel** [comment] 2023-09-07 12:44
I've looked at a few scrapbook post and I can't seem to notice this issue. Can you confirm this is still the case?

**Comment by grymmy** [comment] 2023-10-21 00:03
Closing this issue as @JosiasAurel was unable to reproduce it.  Please re-open this issue if you feel it has been closed in error.

**Closed by grymmy** 2023-10-21 00:03 UTC
